import './globals.css'
import Header from './components/Header/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
console.log(Header)

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='font-plusJakarta'>
        <Header/>
        {children}
      </body>
    </html>
  )
}
