import './globals.css'

import Header from './components/Header/Header'
import Providers from './core/utils/providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='font-plusJakarta'>
        <Providers>

          <Header />
          {children}
        </Providers>

      </body>
    </html>
  )
}
